### ISSUE TITLE
sudden reboots

### ISSUE THREAD

**Issue by barryrowlingson** [katakombi/LinuxMint-t490s#3]
Colleague has just got a Lenovo T490s (says Type 20NY on the bottom) and after installing Linux complained it was rebooting for no apparent reason. I've re-installed Linux Mint from scratch with no proprietary drivers and it was stable for a few hours but then rebooted. There's nothing in kern.log or syslog - just the usual messages every few minutes and then suddenly the first `[ 0.000000] microcode:...` log message from the reboot. No kernel panic, nothing. Not even fan noise indicating overheating which might be a cause of a sudden reboot.

Happens with the latest kernel (5.3) and 5.0. All firmwares seem up to date with fwupdmgr. Am stuck, and about to recommend he installs Windows and if it still crashes then he's got a case for a hardware fault. Other ideas welcome.

**Comment by katakombi** [comment]
I've never seen those except when undervolting. Is undervolting involved?

**Comment by barryrowlingson** [comment]
I've done nothing except install Mint (and colleague had the trouble with Ubuntu) and left all the defaults. If its undervolting its nothing I've done. Am thrashing it now with sysbench to see if that triggers it. But it was idle the last two times it crashed. Will run a memtest and then give up... thanks.

**Comment by katakombi** [comment]
Sadly I don't own the machine any more. Might be a kernel issue, you might try to downgrade to 4.18 and check if that works!

**Comment by barryrowlingson** [comment]
thanks I'm trying that!
